import open3d as o3d
import cv2
import os
from pathlib import Path
import re
from tqdm import tqdm
import numpy as np
# --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# 1. CONFIGURATION: Adjust these settings to your needs
# --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

# --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# 1. CONFIGURATION: Adjust these settings to your needs
# --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

# Folder containing your sequence of .ply files
INPUT_FOLDER = "/home/mingxi/data/realworld/test/output/episode_20250703_125651_170/pcd"

# Path for the output video file
OUTPUT_VIDEO_PATH = "/home/mingxi/data/realworld/b.mp4"

# Frames per second for the output video
VIDEO_FPS = 15

# Resolution of the output video (width, height)
VIDEO_RESOLUTION = (800, 600)

# File pattern to search for. "*.ply" is common.
FILE_PATTERN = "*.ply"

# Temporary folder to store intermediate rendered images
TEMP_IMAGE_FOLDER = "/home/mingxi/data/realworld/temp_pcd_renders"

# --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# 1.5 (NEW) SET A CUSTOM CAMERA VIEWPOINT
# --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
# Path to the camera parameters file generated by get_view_point.py
# If this file exists, it will be used. If not, a default view is used.
CUSTOM_VIEWPOINT_FILE = "vision_utils/camera_viewpoint.json"
# --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---


def sorted_alphanumeric(data):
    """
    Helper function to sort filenames in a natural, alphanumeric order.
    """
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [convert(c) for c in re.split('([0-9]+)', key)]
    return sorted(data, key=alphanum_key)

def create_point_cloud_video():
    """
    Finds a sequence of .ply files, renders each one from a fixed camera angle,
    and compiles the rendered images into an MP4 video.
    """
    print("--- Point Cloud to Video Creator ---")

    # 2. Find and sort the input point cloud files
    print(f"Searching for '{FILE_PATTERN}' files in '{INPUT_FOLDER}'...")
    pcd_files = [str(p) for p in Path(INPUT_FOLDER).glob(FILE_PATTERN)]
    
    if not pcd_files:
        print(f"Error: No files matching '{FILE_PATTERN}' found in '{INPUT_FOLDER}'.")
        return

    sorted_pcd_paths = [os.path.join(INPUT_FOLDER, f) for f in sorted_alphanumeric([os.path.basename(f) for f in pcd_files])]
    print(f"Found {len(sorted_pcd_paths)} point cloud files.")

    # 3. Set up the Open3D visualizer
    vis = o3d.visualization.Visualizer()
    vis.create_window(width=VIDEO_RESOLUTION[0], height=VIDEO_RESOLUTION[1], visible=False)
    
    # Load the first point cloud to add a geometry
    pcd = o3d.io.read_point_cloud(sorted_pcd_paths[0])
    vis.add_geometry(pcd)
    
    # --- --- --- --- --- --- --- --- --- --- --- --- ---
    # (MODIFIED) Load custom camera parameters if the file exists
    # --- --- --- --- --- --- --- --- --- --- --- --- ---
    view_control = vis.get_view_control()
    if os.path.exists(CUSTOM_VIEWPOINT_FILE):
        print(f"Loading custom viewpoint from '{CUSTOM_VIEWPOINT_FILE}'...")
        cam_params = o3d.io.read_pinhole_camera_parameters(CUSTOM_VIEWPOINT_FILE)
        view_control.convert_from_pinhole_camera_parameters(cam_params, allow_arbitrary=True)
    else:
        print("Custom viewpoint file not found. Using default view.")
        # This part is kept as a fallback
        view_control.set_zoom(0.6)
    
    # Store camera parameters to apply to all frames
    cam_params = view_control.convert_to_pinhole_camera_parameters()
    # --- --- --- --- --- --- --- --- --- --- --- --- ---

    os.makedirs(TEMP_IMAGE_FOLDER, exist_ok=True)
    print(f"Temporary image folder created at: {TEMP_IMAGE_FOLDER}")

    # 4. Render each point cloud and save as an image
    print("Rendering frames...")
    for i, pcd_path in enumerate(tqdm(sorted_pcd_paths, desc="Rendering Frames")):
        pcd = o3d.io.read_point_cloud(pcd_path)
        
        vis.clear_geometries()
        vis.add_geometry(pcd)
        
        # Apply the consistent camera view
        view_control.convert_from_pinhole_camera_parameters(cam_params, allow_arbitrary=True)
        
        image_path = os.path.join(TEMP_IMAGE_FOLDER, f"frame_{i:05d}.png")
        vis.capture_screen_image(image_path, do_render=True)

    vis.destroy_window()
    
    # 5. Compile the rendered images into a video
    print("Compiling video...")
    img_files = sorted([f for f in os.listdir(TEMP_IMAGE_FOLDER) if f.endswith(".png")])
    
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    video_writer = cv2.VideoWriter(OUTPUT_VIDEO_PATH, fourcc, VIDEO_FPS, VIDEO_RESOLUTION)

    for img_file in tqdm(img_files, desc="Writing Video"):
        img_path = os.path.join(TEMP_IMAGE_FOLDER, img_file)
        frame = cv2.imread(img_path)
        video_writer.write(frame)
        
    video_writer.release()
    print(f"Video saved successfully to: {OUTPUT_VIDEO_PATH}")

    # 6. Clean up
    print("Cleaning up temporary files...")
    for img_file in img_files:
        os.remove(os.path.join(TEMP_IMAGE_FOLDER, img_file))
    os.rmdir(TEMP_IMAGE_FOLDER)
    print("Cleanup complete.")


if __name__ == "__main__":
    if not os.path.exists(INPUT_FOLDER):
        print(f"Creating a dummy data folder: '{INPUT_FOLDER}' for demonstration.")
        os.makedirs(INPUT_FOLDER)
        for i in range(20):
            points =  (np.random.rand(1000, 3) - 0.5)
            pcd = o3d.geometry.PointCloud()
            pcd.points = o3d.utility.Vector3dVector(points)
            o3d.io.write_point_cloud(os.path.join(INPUT_FOLDER, f"frame_{i}.ply"), pcd)

    create_point_cloud_video()